Ensure all error messages are redirected to stderr.

diff --git a/pylookup b/pylookup
--- a/pylookup
+++ b/pylookup
@@ -243,14 +243,15 @@ for arg in "$@"; do
         case $arg in
             -b|--bare) bare='true'; ;;
             -h|--help) usage; ;;
+            --rebuild) rebuild "$0"; ;;
             --) last='true'; ;;
         esac
     fi
 done
 
 if (( ${#msgs[@]} == 0 )); then
-    echo "${0##*/}: missing operand"
-    echo "Try '${0##*/} --help' for more information."
+    echo "${0##*/}: missing operand" >&2
+    echo "Try '${0##*/} --help' for more information." >&2
     exit 1
 fi
 
